### ISSUE TITLE
What remains

### ISSUE THREAD

**Issue by Benjamin113** [invisiblesushi/ITF20317-SE2018-G1#106]
Hva som står igjen:

- [x] -	Domenebeskrivelse – nesten ferdig
- [x] -	Kravspekk – nesten ferdig (må reformatere nummering)
- [x] -	Se over og endre user stories - Alle går gjennom på mandag 9.04.2018
- [x] -	Use case m/ UML diagram – Benjamin og Magne. Mer informasjon her: #108  
- [x] -	Sekvensdiagram – Trevo. Mer informasjon her: #107 er ferdig, gjenstår bare å legge til på 
                   dokumentet
- [x] -	Klassediagram - Magne. Mer informasjon her: #109 
- [x] -	Tilstandsmaskiner 
- [x] -	Prototype - Daniel. Mer informasjon her: #110 
- [x] -	Forslag til testing - Magne. Mer informasjon her: #111 
- [ ] - Sammendrag
- [ ] -	Formatering - Daniel og Benjamin
