### ISSUE TITLE
Tasks for next meeting

### ISSUE THREAD

**Issue by Swoy** [invisiblesushi/ITF20317-SE2018-G1#18]
_Please complete the following tasks until next meeting (you also need to invite me to this meeting in due time)._

### Tasks
**NOTE:** Extract each of these tasks into individual issues and assign them to the required team members, then add them to the appropriate sprint and complete them in time. Once an item is completed, check it off here and close the issue in question.
- [x] Gather for a workshop and plan ahead for the coming sprints. 
- [x] Create proper tasks (look at #14 for guidance) create sub-tasks and assign them to sprints at least two sprints in advance. 
- [x] Delegate tasks to each team member.
- [x] Complete the domain description with ample visual representations (rike bilder) and make sure it is in an almost finalized state.
- [x] Complete the requirement specification based off of your solution from the domain description.
- [x] Have at least 3-4 user stories completed and I would like to see more than just skeletons for use cases based off of the requirement specification and user stories. _(use the book as help here too)_
- [x] Once these tasks are completed, you invite me for a meeting and we go through the workflow and how far you've come.

**As a side note, please follow the book on how to plan each sprint. I would like to see some proper work in the coming weeks now.** 

Good luck!
