### ISSUE TITLE
Sequence diagram

### ISSUE THREAD

**Issue by Benjamin113** [invisiblesushi/ITF20317-SE2018-G1#34]
| Sequence diagram |
|:----------|
|_Vi skal ha et ferdig løsningsforslag med klassediagram og sekvensdiagram basert på tidligere leveranser_; |
|Write sequence diagrams|
## Sequence diagram
_Create sequence diagrams._

| Notat|
|:----------|
| Dette er en "umbrella issue" for sekvens diagram   |
Informasjon om sekvensdiagrammer : (les her: #51) 

### Oppgaver for denne tasken
- [x] Brainstorming. Mer om denne oppgaven finner du her: #56 
- [x] Authorization. Mer om denne oppgaven finner du her:  #53 
- [x] Barrier
- [x] Robot parking. Mer om denne oppgaven finner du her:  #54 
- [x] Robot pick-up. Mer om denne oppgaven finner du her:  #55 
- [x] Skrive ferdig løsningsforslag
- [x] More...
_Det er verdt å notere seg at deloppgavene skal være like gjennomtenkte. De skal reflektere user stories e.l. fra boka hvor dette er nødvendig._

### Beskrivelse
Dokument med ferdig løsningsforslag samt klassediagram og sekvensdiagram basert på forrige leveranser.

Klassediagram skal dekke helheten i systemet og det skal være med en tekstlig beskrivelse for 2 av klassene.  Beskrivelsen skal være av en slik kvalitet at leser får en god forståelse av klassens formål.

Dokumentet skal være på ca 3 sider + diagram.

### Løsningsforslag
_Her skriver dere (over tid) det som blir fremarbeidet gjennom oppgaven som er beskrevet, på en slik måte at det kan benyttes til en eventuell rapport. Om dette er en oppgave som ikke skal inn i rapporten, så skal det skrives en rapport her om hvordan det ble løst og hva som ble gjort, samt resultatet av det som ble gjort._

### Ekstra informasjon
Link til powerpoints om sekvensdiagrammer fra foreleser her: https://drive.google.com/drive/folders/1FkWViDphwvBo5DdQPdfebEXi2kccAMRA 
Link til nedlasting av papyrus - diagramverktøy: https://www.eclipse.org/papyrus/download.html

**Comment by invisiblesushi** [comment]
Kan gruppen legge diagrammene inn på hoveddokumentet?

**Comment by Benjamin113** [comment]
Closing because finished.
