### ISSUE TITLE
Completed user stories

### ISSUE THREAD

**Issue by trevol1** [invisiblesushi/ITF20317-SE2018-G1#38]
## User stories
_ENG_: This is an overview over the _User stories_ we've come up with.
_NOR_: Dette er våre _User stories_.
### Task list
- [x] Lage _User stories_

##### User stories
- [x] Som en bruker, kan jeg bruke smart parkeringssystemet, for å spare tid.
- [x] Som en passasjer, kan jeg bruke kollektivtransport, for å slippe og finne parkeringsplass i sentrum.
- [x] Som en bruker, kan jeg betale med bankkort/Vipps, for å slippe mynt betaling.
- [x] Som en syklist, kan jeg leie sykkel for å være mer miljøvennlig
- [x] Som en elbil bruker, kan jeg lade bilen, for å få en fulladet bil.
- [x] Som konsulent vil jeg parkere bilen min i langtidsparkeringen for å reise i jobbsammenheng.
- [x] Som forelder vil jeg parkere bilen på korttidsparkering for å levere barna i barnehage/skole.
- [x] Som ansatt vil jeg parkere på Grålum når jeg skal på jobb.
- [x] Som kunde vil jeg parkere på korttidsparkering når jeg skal handle i matbutikk.
- [x] Som besøkende kan jeg parkere på Grålum for å besøke Inspiria.
- [x] Som hotellkunde, kan jeg parkere på Grålum for å bo på Quality Hotel.

### Ekstra informasjon
Ta en titt her : http://www.agilemodeling.com/artifacts/userStory.htm (tar for seg både _User stories_ og _Epics_)

**Comment by trevol1** [comment]
1. En sjåfør vil handle gaver fra flere ulike butikker.
2. En bilist er villig til å betale for en bra parkering. 
3. Man kan få vite om det er ledig parkeringsplass uavhengig av hvor man er.
4. Som en bruker vil jeg kunne betale med Vipps.
5. Som en bruker vil jeg kunne betale med bankkort.
6. En bilist vil levere barna sine for en aktivitetsdag. 
7. En familie på gjennomreise skal overnatte et nærliggende hotell. Vil ha fulladet el-bilen når de drar neste dag. 
8. En arbeider vil parkere på Grålum for å fraktes til arbeidsplassen sin med kollektivtransport. 
9. En ansatt på Grålum vil fritt navigere seg i området med kollektivtransport.
10. En elbilist vil ha bilen fulladet når vedkommende drar. 
11. En bilist vil ikke bruke for langt tid på finne parkeringsplass

**Comment by Swoy** [comment]
Jeg synes ikke dette er tilstrekkelig, dere må nesten jobbe litt mer med disse (om denne er en faktisk task). Se mitt forslag til endring i OP (original post).

**Comment by invisiblesushi** [comment]
Moved to User Stories #39
