### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by trevol1** [invisiblesushi/ITF20317-SE2018-G1#40]
## Prototype
A prototype is an early sample, model, or release of a product built to test a concept or process or to act as a thing to be replicated or learned from. It is a term used in a variety of contexts, including semantics, design, electronics, and software programming. A prototype is generally used to evaluate a new design to enhance precision by system analysts and users. Prototyping serves to provide specifications for a real, working system rather than a theoretical one. In some design workflow models, creating a prototype (a process sometimes called materialization) is the step between the formalization and the evaluation of an idea.

Mer info om prototype finner du ved å lese læreboka fra s.62!

### Oppgaver for denne Tasken
- [x] Brainstorming om prototype. Mer om denne oppgaven finner du her:  #37 
- [x] Delegere deloppgaver av prototype til hvert gruppemedlem. 
- [x] Gjøre wireframes. Mer om denne oppgaven finner du her: #43 
- [x] Skrive forklarende tekst om prototypen - Booking. Mer om denne oppgaven finner du her: #45 
- [x] Skrive forklarende tekst om prototypen - Parkering. Mer om denne oppgaven finner du her: #46 #47 
- [x] Gjøre ferdig hver deloppgave av prototype.  
- [x] Demo av prototype. Mer om denne oppgaven finner du her: #50 

### Beskrivelse
Skrive om en test scenario av vårt system.
### Løsningsforslag
Hvordan vårt system av parkeringsroboter håndterer kapasiteten under rushtiden.
Reservasjon og kapasitet av trafikk til reservasjon under rushtiden.

**Comment by Swoy** [comment]
@trevol1 Ikke bruk Wikipedia, bruk scholar, ACM eller lignende. Så må dere også samle all informasjon inn i denne oppgaven (ved å redigere OP).

**Comment by trevol1** [comment]
Ok, den er grei

**Comment by Benjamin113** [comment]
Closed because finished. 

After discussing with Terje he crossed us off the list.
