### ISSUE TITLE
System proposed solutions - sequence and class diagram

### ISSUE THREAD

**Issue by trevol1** [invisiblesushi/ITF20317-SE2018-G1#66]
## System proposed solutions - sequence and class diagram
Innlevering for uke 8. Løsningsforslag med sekvens diagrammer og klasse diagrammer med utdypende beskrivelse.

### Oppgaver for denne Tasken
- [x] System proposed solutions. Mer om denne oppgaven finner du  her: #65 
- [x] Sequence diagrams. Mer om denne oppgaven finner du her: #34
- [x] Class diagrams. Mer om denne oppgaven finner du her: #26 

### Beskrivelse
Innlevering for uke 8. Her skal vi ha med en utdypende tekst om vårt løsningsforslag i forhold til disse diagrammene.

### Løsningsforslag
Diagrammene forteller oss hvordan systemet vårt fungerer i praksis. Dette forteller oss i mindre subsystemer. Løsningsforslaget vil være et komplement og en utdypende tekst om våre diagrammer.

**Comment by magfla** [comment]
Closed because the issue is referring to a _delivery_ (school assigment), which has been made over two months ago.
