### ISSUE TITLE
Domain description

### ISSUE THREAD

**Issue by Benjamin113** [invisiblesushi/ITF20317-SE2018-G1#88]
| Domain description |
|:----------|
|_Vi skal fullføre domenebeskrivelsen_; |

## Domenebeskrivelse

| Notat|
|:----------|
| Dette er en "umbrella issue" for domenebeskrivelsen   |
Informasjon om domenebeskrivelser : (les her:) 

### Oppgaver for denne tasken
- [x] Korttidsparkering, les mer #92 
- [x] Langtidsparkering, les mer #93 
- [x] Elbil - lading, les mer #94 
- [x] Sykkelutleie, les mer #95 
- [x] kollektivtransport, les mer #96 

### Beskrivelse
Skrive ferdig ny domenebeskrivelse.
### Løsningsforslag
_Her skriver dere (over tid) det som blir fremarbeidet gjennom oppgaven som er beskrevet, på en slik måte at det kan benyttes til en eventuell rapport. Om dette er en oppgave som ikke skal inn i rapporten, så skal det skrives en rapport her om hvordan det ble løst og hva som ble gjort, samt resultatet av det som ble gjort._

### Ekstra informasjon

**Comment by Benjamin113** [comment]
Closing because finished.
